export const FETCH_IDEAS = 'FETCH_IDEAS';
export const FETCH_IDEAS_SUCCESS = 'FETCH_IDEAS_SUCCESS';
export const FETCH_IDEAS_FAIL = 'FETCH_IDEAS_FAIL';

export const OPEN_IMAGE = 'OPEN_IMAGE';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';

export const OPEN_DRAWER = 'OPEN_DRAWER';